# -*- coding: utf-8 -*-
"""API.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Wx8jBvM6wg7qcqT6RRGvJn6028-vuCmi

INTEGRANTES:
--EDWIN ACOSTA 6000324.   --ALEJANDRO CARDONA 1401340
-- SANTIAGO Gonzales 1401185. -- David Garavito 1401245
"""

pip search tweepy #Para buscar si esta en los repositorios la API de Twitter

pip install tweepy #Instalación de la API de Twitter con pip

import pandas as pd
import numpy as np
import tweepy #Se importa la API de Twitter
import json #Se importa Json para una mejor visualización

"""**Registrarse en https://apps.twitter.com/ y elegir los permisos correspondientes para la app en API Keys donde allí se encontrará los Consumer key, Consumer secret, Access Token y Access Secret**"""

#Se escriben los datos de autenticación como son: Consumer key, Consumer secret, Access Token y Access Secret
consumer_key= "ZZYYYnzLjJ6N1PoPrnIXgUdXXXYYY"
consumer_secret= "MMM999fHj0j9Ca8EQ2WPiNgN9ESH0jl50dffMIxxwqAq02hZZZ000"
access_token= "1313319186324754435-mAh2TsJKXMMYvxN2AdkqeJYxv5WWW111"
access_secret= "NNNNMg7lLp5VMPNl94r7D8LLjchePZTRmPneawaTqPPP888"

#Se realiza la autenticación con las claves para realizar el "consumo" a la API de Twitter
auth = tweepy.OAuthHandler(consumer_key, consumer_secret)
auth.set_access_token(access_token, access_secret)

#Se hace la función con el cuál se realiza todas las extracciones o llamadas a Twitter a través de Tweepy
api_twitter=tweepy.API(auth)
#Declaración de un DataFrame vacío
df=pd.DataFrame(columns=('Fecha de creación', 'Usuario', 'Texto'))
#Obtener Tweets que contenga "Claudia Lopez" o relacionado con ese tópico
for tweet in tweepy.Cursor(api_twitter.search, q="Claudia Lopez", tweet_mode="extended").items(1500):
  df.loc[len(df)]=[tweet.created_at, tweet.user.screen_name, tweet.full_text]#Obtención de los datos más relevantes en el DF: La fecha de creación del Tweet, el usuario que escribió el Tweet y el texto donde contiene lo buscado
print(df)
  #print (json.dumps(tweet._json, indent=2)) #sirve para mostrar todos los parámetros que se guardan en cada Tweet

search_tweets_api:
  account_type: premium
  endpoint: <FULL_URL_OF_ENDPOINT>
  consumer_key: <CONSUMER_KEY>
  consumer_secret: <CONSUMER_SECRET>

search_tweets_30_day_prod:
  account_type: premium
  endpoint: <FULL_URL_OF_ENDPOINT>
  bearer_token: <TOKEN>

"""Bibliografía
https://spaceanalytics.blogspot.com/2018/04/tweepy-python.html
https://www.youtube.com/watch?v=PUgPAM5Ect8
https://github.com/lkuffo/leonardo-youtube/tree/master/Extracci%C3%B3n%20de%20Datos%20de%20Twitter
"""