# -*- coding: utf-8 -*-
"""Proyecto_Final.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1iYuytZmk46B9e-btnORcpw3TSWSi_ZcO

**Objetivo: De acuerdo al modelo Crisp-dm plantear 6 preguntas de negocio predictivas y descriptivas aplicada sobre un dataset de su elección**

**Librerias importadas**
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from scipy import stats
import seaborn as sns

"""## **Dataset**

**Carga de dataset y manejo del dataset**
"""

data = pd.read_csv("nassCDS.csv")
data.head()#exploarmos las 5 primeras filas del data frame

data.shape#dimensiones del data frame, son 26217 filas y 16 columnas.

"""Se verifica el tipo de datos y los valores que tiene cada columna."""

data.info()

"""Se imprimen los datos del dataset


"""

data

"""Se verifican los datos nulos enla columnas que no afectan con la lectura de los mismos"""

data=data.drop(columns=['Unnamed: 0'])

data.isnull().sum()

"""
*   La linea "data.dropna( inplace=True )"  elimina las filas que tengan valores de NaN para que este no afecte en el analisis.
*   "data.isnull().sum()" muestra cuales columnas tienen el valor de NaN
*   Y "data.shape" se muestra el numero total de columnas que quedan despues de eliminar las columnas que no tengan el valor de NaN


"""

data.dropna( inplace=True )
data.isnull().sum()
data.shape

data

"""Se renombran varias columnas para facilitar su llamado al momento de realizar la codigfican de la respuesta a las preguntas de negocio"""

data = data.rename(columns={'dvcat':'velocidad(Km/h)',
                                   'ageOFocc':'Edad','injSeverity':'severidad_heridas','abcat':'deploy_airbag','accRole':'rol_accidente','frontal':'tipo_choque'})

data

"""La correlación entre las variables se hace con el fin de analizar que tanto afectan una con la otra, como podemos ver las mas relacionadas llegan a un valor de 0.48, siendo el año del vehículo y el argumentos de si el airbag se abrió o no al momento del accidente"""

data.corr()#correlacion de todas las variables del dataframe

sns.pairplot(data)

"""## **Preguntas de negocio y solución de las mismas**

### **1. ¿Que es más mortal, chocarse de frente o de lado? (Descriptiva)**

Preliminares
0 = no frontal, 1 = impacto frontal
"""

data.describe()

data.groupby('dead').size()

"""Al agrupar los datos de la columna "dead" y gracias al diagrma se determian que las muertes fueron 1180, es decir 4.5 % de todos los datos"""

data.groupby('dead').size().plot(kind='pie', autopct='%1.1f%%')

"""Se extrae la informacion dentro de un nuevo dataset solo tomando en cuenta las columnas implicadas en la pregunta plantea, para este caso "dead" que muestra si el docutor esta vivo o fallecio, y "tipo choque", seguidamente se le asignan valores de identificacion como 0 y 1 al tipo de choque ya sea de frente o lateral y se muestra el contreo a travez de una tabla
"""

newData = data[["dead","tipo_choque"]]
newData = newData[newData.dead == 'dead']

#Map de los valores 0 y 1 del tipo choque
newData["tipo_choque"] = newData.tipo_choque.map(lambda x: "Lado" if x==0 else "Frontal")
newData.describe()
#newData.head()
#newData.groupby(['dead']).count()

"""**Respuesta pregunta 1:**

De los choques con muertes, el 49.3% fueron choques frontales, y el 50.7% fueron choques laterales,
por lo que podemos deducir que el tipo de choque no afecta en el % de muerte

**RESPONDIENDO A LA PREGUNTA, ES MAS MORTAL CHOCARSE DE LADO.**
"""

newData.groupby('tipo_choque').size().plot(kind='pie', autopct='%1.1f%%')
plt.show()

"""### **2. ¿Que relacion hay entre la velocidad y la edad del conductor? (Descriptiva)**

De igual manera se crea un nuevo dataset con las variables directamente implicadas, como la velocidad y la edad del conductor, seguidamente a la variable velocidad se le asigna un nuevo nombre “speed”, y se imprime la tabla de los valores
"""

newData2 = data[["velocidad(Km/h)","Edad"]]
newData2 = newData2.rename(columns={'velocidad(Km/h)':'speed'})
newData2.groupby("speed").mean()

"""Para poder determina un desultado y oganizar los datos se le asignan valores a los rangos de velocidad, los cuales seguidamente seran contratados con las edades de los coductores"""

newData2["speed"] = newData2.speed.map(lambda x: 5 if x=="1-9km/h" 
                                       else 17 if x=="10-24"
                                       else 32 if x=="25-39"
                                       else 47 if x=="40-54"
                                       else 60 if x=="55+"
                                       else 0
                                       )
newData2.groupby("speed").mean()

newData2.describe()

"""**Respuesta pregunta 2:**

Se busca que correlacion hay entre la edad y la velocidad del accidente, de acuerdo a las graficas generadas se determino un valor de -0.05 por lo tanto no hay ninguna clase de relacion entre estas dos variables
"""

newData2.corr()

sns.pairplot(newData2)

sns.jointplot(x = "Edad", y = "speed", data = newData2);

"""### **3. ¿ De todos los impactos ¿En cuántos se desplego el airbag? (Descriptiva)**"""

#Extraer en un nuevo DF las columnas con las que se va a trabajar
new_Data = data[["airbag","deploy_airbag"]].copy()
new_Data.describe()

"""Se determina la proporción que existe entre los vehículos que tienen airbag y se desplegaron y los que no tenían, la grafica muetra por rangos de colores estos resultados"""

new_Data.groupby(['airbag','deploy_airbag']).size().unstack().plot(kind='bar',stacked=True)
plt.show()

"""Se retiran la cantidad de vehículos que no tenían airbag y solamente se dejaron los que si tenían para saber cuántos de ellos se desplegaron y cuántos no"""

new_Data = new_Data[new_Data.airbag == 'airbag']
new_Data.describe()

"""Se realiza un nuevo grafico para Ver el porcentaje de los vehículos que tenían airbag se desplegaron al momento del accidente"""

new_Data.groupby(['deploy_airbag']).size().plot(kind='pie', y='',autopct='%1.3f%%', title='Airbag desplegado')
plt.show()

"""### **Respuesta pregunta 3:**
Se observa que de un total de 14336 vehículos que poseían airbag solo el 61,377% se desplegó el airbag al momento del accidente

### **Pregunta 4. ¿Cuál es la probabilidad de que un auto sin airbag genere incapacidades o muerte previa? (Predictiva)**

Se realiza un Cambio de los valores numéricos de la columna "severidad_heridas" por el significado de dicho número, con el fin de indentificar la variables y se imprimeme la tabla de las dos coumnas implicadas
"""

#Extraer en un nuevo DF las columnas con las que se va a trabajar
new_Data1 = data[["airbag","severidad_heridas"]].copy()

new_Data1["severidad_heridas"] = new_Data1.severidad_heridas.map(lambda x: 'Ninguno' if x==0
                                       else 'Posible lesión' if x==1
                                       else 'Sin incapacidad' if x==2
                                       else 'Incapacidad' if x==3
                                       else 'Muerto' if x==4
                                       else 'Desconocido' if x==5
                                       else 'Muerte previa'
                                       )
new_Data1.describe()

"""Se muestra la proporción que existe la severidad_heridas y el hecho de que el vehículo tenga airbag, los colores estar proporcionalmente al numero de veces que se abrio el airbag o no sobre la implicacion de la herida"""

new_Data1.groupby(['airbag','severidad_heridas']).size().unstack().plot(kind='bar',stacked=True)
plt.show()

pd.crosstab(new_Data1.severidad_heridas,new_Data1.airbag, margins=True)

tabla_contg=pd.crosstab(new_Data1.severidad_heridas,new_Data1.airbag, margins=True)
Probabilidad=((tabla_contg.iloc[1,1]/tabla_contg.iloc[7,1])+(tabla_contg.iloc[2,1]/tabla_contg.iloc[7,1]))*100
print (Probabilidad)

"""Repuesta pregunta 4:

Hay un 35% de probabilidad de que el no tener airbag se genere un accidente con incapacidades y muerte previa

### **Pregunta 5: ¿Cuál es la probabilidad de que la edad del fallecido en el accidente este entre los 20 y 30 años?**

Se copian los datos y se evalua la columna a la cual se calculara la prioridad asignandole los rangos correspondientes a las edades de 20 a 30 años, seguidamente se imprime un grafico de barras mostrando la cantidad de personas entre ese rango de edades
"""

QP1 = data[["dead","Edad"]].copy()
QP1["Edad"] = QP1.Edad.map(lambda x :  
                           '20 años' if x==20
                                     else 'Mayor a 20 años' if x > 20
                                     else 'Menor a 30 años' if x < 30
                                     else '30 años' if x==30
                                     else 'mayores de 30 años'
                                       )
QP1.groupby(['dead','Edad']).size().unstack().plot(kind='bar',stacked=True)
plt.title("Personas dentro del rango de edad VS Estado")
plt.xlabel('Estado del coductor')
plt.ylabel('Personas')
plt.show('hola')
print("Se observa que la mayoria de personas que sobrevivieron al accidente estan en el rango asignado de 20 a 30 años")
print('')
print("Por su lado aquellos con exactamente esa edad son muy pocas, al igual que la cantidad de fallecidos")

pd.crosstab(QP1.Edad,QP1.dead)

TablaQP1=pd.crosstab(QP1.Edad,QP1.dead)
Prob=((TablaQP1.iloc[1,0]*100)/(TablaQP1.iloc[1,0]+TablaQP1.iloc[1,1]))
print("la probabilidad de que la edad del fallecido en el accidente este entre los 20 y 30 años", Prob)



"""### **Respuesta pregunta 5:**

La cantidad de personas de 20 años vivas despues del accidente son de 933, y fallecidos 29 por lo tanto las personas entre el rango de edad son 19945, valor que corresponde al 95% del total de invididuos

### **Pregunta 6: ¿Cuál es la probabilidad de muerte si la velocidad del impacto supera los 55km/H?**

SE imprime la tabla de relacion entre los valodes de la columna "dead y la velocidad, con el fina de evaluar los rangos planteados anteriormente
"""

QP2 = data[["dead","velocidad(Km/h)"]].copy()
QP2 = QP2.rename(columns={'velocidad(Km/h)':'speed'})
pd.crosstab(QP2.speed,QP2.dead)

TablaQP2=pd.crosstab(QP2.speed,QP2.dead)
Prob2=((TablaQP2.iloc[4,1]*100)/(TablaQP2.iloc[4,0]+TablaQP2.iloc[4,1]))
print("La probabilidad de muerte si la velocidad del impacto supera los 55km/H es: ", Prob2)

"""### **Respuesta pregunta 6:**
Se realiza una regla de 3 con el fina de determinar que el 27% de los accidente provocan muerte sobre el coductor cuando este vas mas alla de los 55Km/h
"""